/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Good: typeof import('./src/components/good.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NBuutton: typeof import('naive-ui')['NBuutton']
    NCard: typeof import('naive-ui')['NCard']
    NCardBody: typeof import('naive-ui')['NCardBody']
    NCardFooter: typeof import('naive-ui')['NCardFooter']
    NCardHeader: typeof import('naive-ui')['NCardHeader']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NRate: typeof import('naive-ui')['NRate']
    NScroll: typeof import('naive-ui')['NScroll']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NScroollbar: typeof import('naive-ui')['NScroollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    Order: typeof import('./src/components/order.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
